### ISSUE TITLE
Can't comment on your blog post?

### ISSUE THREAD

**Issue by FreeEnergyPrincipler** [takyamamoto/PredictiveCoding-RaoBallard-Model#1]
Hello, 
Thank you for your good blog post and repository!
I'm now wondering if I could put some comments on your blog post.
(I think GitHub issues are not a good place to put comments because comments are not issues, just comments)
If you do not intend to open a comment, it's OK. Please let me know about that.
Thank you.

![スクリーンショット 2020-04-25 18 07 53](https://user-images.githubusercontent.com/64305852/80276004-5ef46680-8720-11ea-9f70-22a1d99c0b92.png)

**Comment by takyamamoto** [comment]
Dear FreeEnergyPrinciple

Thank you for contact. I've never seen this error before. I checked with
multiple computers but I didn't see any errors. This is probably a
temporary error. The type of browser may also be a factor. I checked it in
Chrome and Edge.

Also, the commenting system we use on this website is called utterances,
and you need to be logged in to GitHub to comment.

Best regards,

2020年4月25日(土) 18:15 FreeEnergyPrincipler <notifications@github.com>:

**Comment by FreeEnergyPrincipler** [comment]
Dear Mr. @takyamamoto,

Thank you for your commenting back.
Yes, I had logged in to GitHub but the commenting system didn't work (, when I was using Chrome).
And now I've got the same error...
I don't know why this happens. I'll check it later again.

Anyway, great job again in your implementation of the Predictive Coding!
Recently, I think, researchers have got more interested in predictive coding (like un- or self-supervised learning framework, video prediction, its biological plausibility, optical illusion(?), etc).
I'd like to see your implementation and/or reproduction as some sorts of predictive coding series.

Do you have a plan to write predictive coding blog posts series?
If so, I’m looking forward to reading the posts.

Thank you.

**Comment by takyamamoto** [comment]
Thank you for your comment.

I confirmed the bug and fixed it. I think you can comment on articles.

By the way, there's an article about predictive coding which I wrote when I was a freshman, which comes up at the top of a Google search. 

https://omedstu.jimdofree.com/2018/08/17/%E4%BA%88%E6%B8%AC%E7%AC%A6%E5%8F%B7%E5%8C%96-predictive-coding-%E3%81%A8%E3%81%AF%E4%BD%95%E3%81%8B/

I think the content of this article is not good. Therefore, I wrote an article about the "Rao & Ballard model" for the purpose of revising this article.

I plan to write about the free energy principle, relationship with Kalman filter or Linear predictive coding, deep predictive coding networks (such as PredNet), etc.

Especially, There are some excellent introductions to the free energy principle, such as Dr. Yoshida's and JNNS' s articles, but in my articles, I would like to be able to give implementations in Python (or Julia) as well as formulas.
